from typing import Literal

from pydantic import BaseModel, Field


class PitchClaim(BaseModel):
    """
    A factual or policy claim made in the pitch.

    Every claim will later be independently audited against
    the selected policy document.
    """

    claim: str = Field(
        description="A single factual or policy claim."
    )

    claim_type: Literal[
        "company_fact",
        "policy_fact",
        "recommendation",
        "inference",
    ]

    source_chunk_ids: list[str] = Field(
        default_factory=list,
        description=(
            "Relevant policy evidence chunk IDs used to "
            "support this claim."
        ),
    )


class PitchSlide(BaseModel):
    """
    One slide in the generated client pitch.
    """

    slide_number: int = Field(
        ge=1,
        le=5,
    )

    title: str

    subtitle: str | None = None

    key_points: list[str] = Field(
        min_length=1,
        max_length=6,
    )

    claims: list[PitchClaim] = Field(
        default_factory=list
    )


class PitchContent(BaseModel):
    """
    Complete structured pitch generated by the pitch agent.
    """

    company_name: str

    policy_provider: str

    policy_product: str | None = None

    recommendation: str

    recommendation_rationale: str

    slides: list[PitchSlide] = Field(
        min_length=3,
        max_length=5,
    )